[agent]
  interval = "10s"
  flush_interval = "10s"
  debug = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["iot/sensor/aggregate"]
  data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "sensor_data"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "avg"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "dominant_hz"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "sample_rate_hz"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "window_ms"
      type = "int"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "timestamp"
      type = "int"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "my-super-secret-token"
  organization = "iot-project"
  bucket = "sensor-data"